---
- hosts: all
  vars:
    postgres_user: team9
    postgres_password: team9
    postgres_db: webshop


  tasks:
    - name: add GPG key
      ansible.builtin.apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: 68576280
        state: present

    - name: Install python libs
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-dev
          - python3-virtualenv
          - libaio-dev
          - libpq-dev
          - redis-server
        state: latest
        update_cache: true

    - name: Install specified python requirements in indicated (virtualenv)
      pip:
        requirements: /vagrant/requirements/dev.txt
        virtualenv: /home/vagrant/venv
        virtualenv_python: python3

    - name: Install PostgreSQL
      ansible.builtin.apt:
        pkg:
          - postgresql
          - postgresql-contrib
          - postgresql-server-dev-all
          - python3-psycopg2
          - acl
        state: latest

    - name: Start and enable postgres
      ansible.builtin.service:
        name: postgresql
        enabled: yes
        state: started

    - name: Create postgres user
      community.postgresql.postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
      become: yes
      become_user: postgres

    - name: Create db
      include_tasks: postgres.yml

    - name: Exporting db url to env
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^DATABASE_URL="
        line: "DATABASE_URL=postgres://{{ postgres_user }}:{{ postgres_password }}@127.0.0.1:5432/{{ postgres_db }}"

    - name: Exporting redis url to env
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^REDIS_URL="
        line: "REDIS_URL=redis://127.0.0.1:6379/0"


  handlers:
    - name: postgresql restart
      ansible.builtin.service:
        name: postgresql
        enabled: yes
        state: restart
        become: yes
